GET http://localhost:8081/products
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzYXJhQGdtYWlsLmNvbSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTc3OTkwMjYyNCwiZXhwIjoxNzc5OTA2MjI0fQ.e3N8r4H15z9B-ENqesn2pzajOx_zGrnq1SWq5P03qL2Wp8jpvCC_orY25iYtDCGoFmxj0oQR8uYXeHfTtlBOsx6WBpPxDiRjK0WADXgtrk04HXOb4WvXDE38dzcuQ2mp4cdDSoHgLsnVXv4-WPz4hCBErpOYvh2TQsnvCRL1keT_FY7Nlu5fQu9JzdsZ7JhpJj5XSQdb9uIVv2IeR96Ub51dE6jIT6tg2ssyRzayOJhwpR-e06AwxFIaqGbKEAknEKIXQdq7_d2aBAg8SSOc9U6ee__eWC6MXTrct258ZRnOTZfaSeK322fecpXex4tRch1_gzWLmOxLA_qrUpSozA