# Local development configuration (H2 in-memory)
spring.datasource.url=jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate & Data SQL initialization
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Auth / JWT
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/auth/jwks

# Server
server.port=8082
server.forward-headers-strategy=framework